### ISSUE TITLE
Modify invitations emails

### ISSUE THREAD

**Issue by microstudi** [Platoniq/decidim-uclg#12]
- [ ] Invitation emails to private assemblies should be sent only in special cases (this is configurable in `secrets.yml`)
- [ ] The text sent should be also configurable

```yaml
default: &default
  # hacking user private invitations, use false to avoid sending invitation 
  # use a mail template identifier otherwise
  # 
  private_invites:
    localhost:
      default: false # invite_private_user
      assemblies:
        numquam-officia: invite_private_user
        perferendis-voluptatem: world_council
    www.uclgmeets.org:
      default: false
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
   
```
